services:
  app:
    build: .
    ports:
      - 3333:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    networks:
      - urban
  db:
    image: mysql
    networks:
      - urban
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  urban:
    driver: "bridge"